In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7],[8],[9]])
C=np.dot(A,B)
C

array([[ 50],
       [122]])

In [3]:
X=np.array([[1,2],[3,4],[5,6]])
Y=np.array([[7,9],[8,10]])
Z=np.dot(X,Y)
Z

array([[ 23,  29],
       [ 53,  67],
       [ 83, 105]])

In [4]:
X=np.array([2.0, 3.0])
W=np.array([[0.1, 0.2, 0.1],[0.2, 0.1, 0.2]])
B=np.array([0.1, 0.2, 0.2])
A=np.dot(X,W)+B

In [5]:
A

array([0.9, 0.9, 1. ])

In [6]:
def sigmoid(x):
    return 1/(np.exp(-x))

In [7]:
Z=sigmoid(A)

In [8]:
print(Z)

[2.45960311 2.45960311 2.71828183]


In [9]:
W2=np.array([[0.1, 0.2],[0.1, 0.5],[0.3, 0.2]])
B2=np.array([0.2, 0.1])
A2=np.dot(Z,W2)+B2
Z2=sigmoid(A2)

In [10]:
print(A2)
print(Z2)

[1.50740517 2.36537854]
[ 4.51499993 10.64806881]


In [12]:
W3=np.array([[0.1, 0.5],[0.3, 0.2]])
B3=np.array([0.3, 0.1])
A3=np.dot(Z2,W3)+B3

In [13]:
def relu(x):
    return np.maximum(0,x)

In [14]:
Y=relu(A3)

In [15]:
print(A3)
print(Y)

[3.94592064 4.48711373]
[3.94592064 4.48711373]
